### ISSUE TITLE
Files missing for H3.6m long term prediction 

### ISSUE THREAD

**Issue by zaverichintan** [limaosen0/DMGNN#2]
The files are missing in:
[Long term](https://github.com/limaosen0/DMGNN/tree/master/h36m-long)

Can I place files from [Short term](https://github.com/limaosen0/DMGNN/tree/master/h36m-short) in the long term folder?

What are other changes ?

**Comment by Charles-9802** [comment]
Do you know what changes need to be made now? Thanks!

**Comment by zaverichintan** [comment]
@xuxuzhangasas try copying the files in Long term folder and edit https://github.com/limaosen0/DMGNN/blob/67048dd1c59d4d165eade99419aa09c745b9d6ce/h36m-short/processor/processor.py#L160
First train the model and then do inference in similar fashion

**Comment by xuxuzhangasas** [comment]
Firstly, thank you very much for your reply. Secondly, maybe you said I should try copying the files in short term folder and edit? But I get an error when I test, Do you know how to deal with it?
Unknown Arguments: edge_importance_weighting
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    p = Processor(sys.argv[2:])
  File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-long\processor\processor.py", line 24, in __init__
    self.load_arg(argv)
  File "D:\DMGNN\dwgnn-master\DMGNN-master\h36m-long\processor\io.py", line 37, in load_arg
    assert k in key
AssertionError

**Comment by Charles-9802** [comment]
Thanks!
